name: Deploy Line Detection Visualizations to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write # Needed to checkout the gh-pages branch
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch for history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Prepare deployment files
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          mkdir -p ./gh-pages/$SHORT_SHA
          cp -r ./output_visualizations/* ./gh-pages/$SHORT_SHA/

          # Generate the new index.html for the root
          echo "<html><head><title>Deployment History</title><style>body { font-family: sans-serif; }</style></head><body><h1>Deployment History</h1><ul>" > ./gh-pages/index.html
          # Find all subdirectories and create links
          find ./gh-pages -mindepth 1 -maxdepth 1 -type d | sort -r | while read -r dir; do
            dir_name=$(basename "$dir")
            echo "<li><a href='./$dir_name/'>$dir_name</a></li>" >> ./gh-pages/index.html
          done
          echo "</ul></body></html>" >> ./gh-pages/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './gh-pages'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4