name: Deploy Vectorization Showcase to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

permissions:
  contents: write # Needed to checkout/push to branches
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch (for source code)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git log
          submodules: recursive # Initialize and update submodules

      - name: Checkout history branch (for deployment content)
        uses: actions/checkout@v4
        with:
          ref: history
          path: .history
          # Use a token with write permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
        with:
          version: '1.7.1'

      - name: Debug PATH and jq installation
        run: |
          echo "PATH: $PATH"
          which jq

      - name: Prepare deployment files
        run: bash .github/scripts/generate_history.sh
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          GITHUB_SHA: ${{ github.sha }}
          HISTORY_PATH: .history
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
