name: Deploy Vectorization Showcase to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

permissions:
  contents: write # Needed to checkout/push to branches
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Remove .gitmodules before checkout (preemptive)
        run: |
          if [ -f .gitmodules ]; then
            rm .gitmodules
            echo "Removed .gitmodules from workspace before checkout."
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Deploy content to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output_for_deployment
          publish_branch: gh-pages
          # The following option creates a clean deployment branch, removing all old files.
          force_orphan: true