name: Deploy Vectorization Showcase to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

permissions:
  contents: write # Needed to checkout/push to branches
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Remove .gitmodules before checkout (preemptive)
        run: |
          if [ -f .gitmodules ]; then
            rm .gitmodules
            echo "Removed .gitmodules from workspace before checkout."
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify the Python version you are using

      - name: Install Python dependencies
        run: pip install -r ./line_detection_comparison/requirements.txt

      - name: Checkout history branch (for deployment content)
        uses: actions/checkout@v4
        with:
          ref: history
          path: .history
          submodules: false # Explicitly disable submodule processing
          # Use a token with write permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean .gitmodules from .history if exists
        run: |
          if [ -f .history/.gitmodules ]; then
            rm .history/.gitmodules
            echo "Removed .history/.gitmodules to prevent submodule errors."
          fi

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
        with:
          version: '1.7.1'

      - name: Debug PATH and jq installation
        run: |
          echo "PATH: $PATH"
          which jq

      - name: Prepare deployment files
        run: bash .github/scripts/generate_history.sh
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          GITHUB_SHA: ${{ github.sha }}
          HISTORY_PATH: .history
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .history
          publish_branch: gh-pages