name: Deploy Vectorization Showcase to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

permissions:
  contents: write # Needed to checkout/push to the history branch
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch (for source code)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git log

      - name: Checkout history branch (for data file and deployment content)
        uses: actions/checkout@v4
        with:
          ref: history
          path: .history

      - name: Prepare deployment files
        id: prep
        run: bash .github/scripts/generate_history.sh
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          GITHUB_SHA: ${{ github.sha }}
          HISTORY_PATH: .history

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Explicitly set the branch
          publish_dir: .history # Publish the content of the .history directory
          force_orphan: false # Crucial: do NOT orphan, keep history
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          cname: '' # Disable Jekyll