name: Deploy Line Detection Visualizations to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write # Needed to checkout the gh-pages branch and get commit info
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git log

      - name: Checkout gh-pages branch for history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Prepare deployment files
        run: bash .github/scripts/generate_history.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './gh-pages'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
